# Run Unit Tests and Deploy Package to Test PyPI on Pushes to Main
name: Deploy Package To Test PyPI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  unit-test-pytest:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v6
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      # Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-branch
      
      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
  publish-test-pypi:
    needs: unit-test-pytest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}  # checkout exact tag
          fetch-depth: 0  # need full history for version detection

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Install development dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Build the package with hatch
      - name: Build package
        run: hatch build

      # Run formatter
      - name: Run ruff formatter
        run: |
          ruff check .

      # Publish to TestPyPI
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      # Test the installation from TestPyPI
      - name: Test install from TestPyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            canadataClean