# Run Unit Tests and Deploy Package to Test PyPI on Pushes to Main
name: Deploy Package To Test PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-test-pytest:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      # Run pytest with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term --cov-branch
      
      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      # Run formatter
      - name: Run ruff formatter
        run: |
          ruff check .

  pypi-test:
    needs: unit-test-pytest
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install development dependencies including hatch
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Build the package with hatch
      - name: Build package
        run: hatch build

      # Publish to TestPyPI
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      # Test the installation from TestPyPI
      - name: Test install from TestPyPI
        # if: steps.release.outputs.released == 'true'
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            canadataClean